// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/rest.proto
// </auto-generated>
// Original file comments:
// Copyright 2015 gRPC authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Rest {
  /// <summary>
  /// The CRUDs service definition.
  /// </summary>
  public static partial class CRUDs
  {
    static readonly string __ServiceName = "rest.CRUDs";

    static readonly grpc::Marshaller<global::Rest.QryProxy> __Marshaller_QryProxy = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Rest.QryProxy.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Rest.TblaProxy> __Marshaller_TblaProxy = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Rest.TblaProxy.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Rest.AHPproxy> __Marshaller_AHPproxy = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Rest.AHPproxy.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Rest.AFBproxy> __Marshaller_AFBproxy = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Rest.AFBproxy.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Rest.AFDproxy> __Marshaller_AFDproxy = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Rest.AFDproxy.Parser.ParseFrom);

    static readonly grpc::Method<global::Rest.QryProxy, global::Rest.TblaProxy> __Method_TblaFill = new grpc::Method<global::Rest.QryProxy, global::Rest.TblaProxy>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "TblaFill",
        __Marshaller_QryProxy,
        __Marshaller_TblaProxy);

    static readonly grpc::Method<global::Rest.TblaProxy, global::Rest.TblaProxy> __Method_TblaUpdate = new grpc::Method<global::Rest.TblaProxy, global::Rest.TblaProxy>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TblaUpdate",
        __Marshaller_TblaProxy,
        __Marshaller_TblaProxy);

    static readonly grpc::Method<global::Rest.QryProxy, global::Rest.AHPproxy> __Method_AHPfill = new grpc::Method<global::Rest.QryProxy, global::Rest.AHPproxy>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "AHPfill",
        __Marshaller_QryProxy,
        __Marshaller_AHPproxy);

    static readonly grpc::Method<global::Rest.AHPproxy, global::Rest.AHPproxy> __Method_AHPupdate = new grpc::Method<global::Rest.AHPproxy, global::Rest.AHPproxy>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AHPupdate",
        __Marshaller_AHPproxy,
        __Marshaller_AHPproxy);

    static readonly grpc::Method<global::Rest.QryProxy, global::Rest.AFBproxy> __Method_AFBfill = new grpc::Method<global::Rest.QryProxy, global::Rest.AFBproxy>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "AFBfill",
        __Marshaller_QryProxy,
        __Marshaller_AFBproxy);

    static readonly grpc::Method<global::Rest.AFBproxy, global::Rest.AFBproxy> __Method_AFBupdate = new grpc::Method<global::Rest.AFBproxy, global::Rest.AFBproxy>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AFBupdate",
        __Marshaller_AFBproxy,
        __Marshaller_AFBproxy);

    static readonly grpc::Method<global::Rest.QryProxy, global::Rest.AFDproxy> __Method_AFDfill = new grpc::Method<global::Rest.QryProxy, global::Rest.AFDproxy>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "AFDfill",
        __Marshaller_QryProxy,
        __Marshaller_AFDproxy);

    static readonly grpc::Method<global::Rest.AFDproxy, global::Rest.AFDproxy> __Method_AFDupdate = new grpc::Method<global::Rest.AFDproxy, global::Rest.AFDproxy>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AFDupdate",
        __Marshaller_AFDproxy,
        __Marshaller_AFDproxy);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Rest.RestReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CRUDs</summary>
    public abstract partial class CRUDsBase
    {
      public virtual global::System.Threading.Tasks.Task TblaFill(global::Rest.QryProxy request, grpc::IServerStreamWriter<global::Rest.TblaProxy> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Rest.TblaProxy> TblaUpdate(global::Rest.TblaProxy request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task AHPfill(global::Rest.QryProxy request, grpc::IServerStreamWriter<global::Rest.AHPproxy> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Rest.AHPproxy> AHPupdate(global::Rest.AHPproxy request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task AFBfill(global::Rest.QryProxy request, grpc::IServerStreamWriter<global::Rest.AFBproxy> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Rest.AFBproxy> AFBupdate(global::Rest.AFBproxy request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task AFDfill(global::Rest.QryProxy request, grpc::IServerStreamWriter<global::Rest.AFDproxy> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Rest.AFDproxy> AFDupdate(global::Rest.AFDproxy request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CRUDs</summary>
    public partial class CRUDsClient : grpc::ClientBase<CRUDsClient>
    {
      /// <summary>Creates a new client for CRUDs</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CRUDsClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CRUDs that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CRUDsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CRUDsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CRUDsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Rest.TblaProxy> TblaFill(global::Rest.QryProxy request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TblaFill(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Rest.TblaProxy> TblaFill(global::Rest.QryProxy request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_TblaFill, null, options, request);
      }
      public virtual global::Rest.TblaProxy TblaUpdate(global::Rest.TblaProxy request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TblaUpdate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Rest.TblaProxy TblaUpdate(global::Rest.TblaProxy request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TblaUpdate, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Rest.TblaProxy> TblaUpdateAsync(global::Rest.TblaProxy request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TblaUpdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Rest.TblaProxy> TblaUpdateAsync(global::Rest.TblaProxy request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TblaUpdate, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Rest.AHPproxy> AHPfill(global::Rest.QryProxy request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AHPfill(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Rest.AHPproxy> AHPfill(global::Rest.QryProxy request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_AHPfill, null, options, request);
      }
      public virtual global::Rest.AHPproxy AHPupdate(global::Rest.AHPproxy request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AHPupdate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Rest.AHPproxy AHPupdate(global::Rest.AHPproxy request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AHPupdate, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Rest.AHPproxy> AHPupdateAsync(global::Rest.AHPproxy request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AHPupdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Rest.AHPproxy> AHPupdateAsync(global::Rest.AHPproxy request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AHPupdate, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Rest.AFBproxy> AFBfill(global::Rest.QryProxy request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AFBfill(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Rest.AFBproxy> AFBfill(global::Rest.QryProxy request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_AFBfill, null, options, request);
      }
      public virtual global::Rest.AFBproxy AFBupdate(global::Rest.AFBproxy request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AFBupdate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Rest.AFBproxy AFBupdate(global::Rest.AFBproxy request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AFBupdate, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Rest.AFBproxy> AFBupdateAsync(global::Rest.AFBproxy request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AFBupdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Rest.AFBproxy> AFBupdateAsync(global::Rest.AFBproxy request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AFBupdate, null, options, request);
      }
      public virtual grpc::AsyncServerStreamingCall<global::Rest.AFDproxy> AFDfill(global::Rest.QryProxy request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AFDfill(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Rest.AFDproxy> AFDfill(global::Rest.QryProxy request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_AFDfill, null, options, request);
      }
      public virtual global::Rest.AFDproxy AFDupdate(global::Rest.AFDproxy request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AFDupdate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Rest.AFDproxy AFDupdate(global::Rest.AFDproxy request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AFDupdate, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Rest.AFDproxy> AFDupdateAsync(global::Rest.AFDproxy request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AFDupdateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Rest.AFDproxy> AFDupdateAsync(global::Rest.AFDproxy request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AFDupdate, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CRUDsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CRUDsClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CRUDsBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_TblaFill, serviceImpl.TblaFill)
          .AddMethod(__Method_TblaUpdate, serviceImpl.TblaUpdate)
          .AddMethod(__Method_AHPfill, serviceImpl.AHPfill)
          .AddMethod(__Method_AHPupdate, serviceImpl.AHPupdate)
          .AddMethod(__Method_AFBfill, serviceImpl.AFBfill)
          .AddMethod(__Method_AFBupdate, serviceImpl.AFBupdate)
          .AddMethod(__Method_AFDfill, serviceImpl.AFDfill)
          .AddMethod(__Method_AFDupdate, serviceImpl.AFDupdate).Build();
    }

  }
}
#endregion
